replicaCount: 1
image:
  repository: [ECR Repositroy]
  tag: [Image Tag]
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
  name: user-service-account
  annotations:
    eks.amazonaws.com/role-arn: [IAM Role]
service:
  activeService: app-active
  previewService: app-preview
  type: ClusterIP
  port: 8001
containerPort: 8001
configMapName: url-config
