replicaCount: 1
image:
  repository: [ECR Repository]
  tag: [Image Tag]
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
  name: streamlit-service-account
  annotations:
    eks.amazonaws.com/role-arn: [IAM Role]
service:
  activeService: app-active
  previewService: app-preview
  type: ClusterIP
  port: 8501
containerPort: 8501
configMapName: url-config
